Ext.define('pxp.model.Ingreso', {
    extend: 'Ext.data.Model',
    requires: [
        'Ext.data.Model'
    ],
    config: {
    	     idProperty :'id_movimiento',
	        fields: [
						{name:'id_movimiento', type: 'numeric'},
						{name:'estado_reg', type: 'string'},
						{name:'tipo', type: 'string'},
						{name:'id_casa_oracion', type: 'numeric'},
						{name:'concepto', type: 'string'},
						{name:'obs', type: 'string'},
						{name:'fecha', type: 'date',dateFormat:'Y-m-d'},
						{name:'id_estado_periodo', type: 'numeric'},
						{name:'fecha_reg', type: 'date',dateFormat:'Y-m-d H:i:s.u'},
						{name:'id_usuario_reg', type: 'numeric'},
						{name:'fecha_mod', type: 'date',dateFormat:'Y-m-d H:i:s.u'},
						{name:'id_usuario_mod', type: 'numeric'},
						{name:'usr_reg', type: 'string'},
						{name:'usr_mod', type: 'string'},
						'id_tipo_movimiento_mantenimiento' ,
				        'id_movimiento_det_mantenimiento',
				        'monto_mantenimiento',
				        'id_tipo_movimiento_especial',
				        'id_movimiento_det_especial',
				        'monto_especial',
				        'id_tipo_movimiento_piedad',
				        'id_movimiento_det_piedad',
				        'monto_piedad',
				        'id_tipo_movimiento_construccion',
				        'id_movimiento_det_construccion',
				        'monto_construccion',
				        'id_tipo_movimiento_viaje',
				        'id_movimiento_det_viaje',
				        'monto_viaje', 'monto_dia','tipo_reg',
				        'total_mantenimiento','total_construccion','total_viaje','total_especial','total_dia','total_piedad',
				        'id_obrero',
					    'desc_obrero',
					    'estado',
					    'desc_casa_oracion',
	                    'mes',
	                    'estado_periodo',
	                    'id_gestion',
	                    'gestion','id_ot','desc_orden','nombre_tipo_mov_ot','id_tipo_movimiento_ot']
     }  
});